site_name: MilleNuits
site_author: Amine

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair

extra_css:
  - stylesheets/extra.css

nav:
  - Accueil: index.md
  - SP2 - Mille Nuits:
      - Mission 1 - Documentation:
          - Comparatif Editeurs: SP2-MilleNuits/mission1/comparatif.md
          - Installation MkDocs: SP2-MilleNuits/mission1/installMk.md
      - Mission 2 - Postes Clients:
          - Masterisation: SP2-MilleNuits/mission2/master.md
          - Explication Sysprep: SP2-MilleNuits/mission2/sysprep.md
      - Mission 3 - Déploiement:
          - Comparatif Solutions: SP2-MilleNuits/mission3/comparatif.md
          - Fonctionnement FOG: SP2-MilleNuits/mission3/fonctionnement_fog.md
          - Solution FOG: SP2-MilleNuits/mission3/fog.md
      - Mission 4 - Incidents:
          - Outil GLPI: SP2-MilleNuits/mission4/glpi.md
          - Procédures: SP2-MilleNuits/mission4/procedures.md
          - Users: SP2-MilleNuits/mission4/users.md
  - SP3 - Mille Nuits:
      - Mission 2 - Réseau:
          - Simulation Cisco Packet Tracer: SP3-MilleNuits/mission2/cisco.md
          - Linux DHCP ISC: SP3-MilleNuits/mission2/isc.md
          - Linux DHCP KEA: SP3-MilleNuits/mission2/kea.md

